const bringLayouts = [
  {
    shapes: [],
    url: 'assets/layouts/blank.png',    
    id: 0
  },
  {
    shapes: [
        { type: 'text',
          content: 'Click to add Title',
          x: '30%',
          y: '50%',
          w: '200px',
          h: '50px',
        },
    ],
    url: 'assets/layouts/title.png',
    id: 1
  },
  {
    shapes: [
        { type: 'text',
          content: 'Click to add Title',
          x: '30%',
          y: '10%',
          w: '100px',
          h: '30px',          
        },
        { type: 'text',
          content: 'Click to add Text',
          x: '20%',
          y: '43%',
          w: '100px',
          h: '80px',          
        },
        { type: 'text',
          content: 'Click to add Text',
          x: '20%',
          y: '76%',
          w: '100px',
          h: '80px',         
        },
        { type: 'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '66%',
          y: '66%',
          w: '200px',
          h: '200px',          
        },
    ],
    url: 'assets/layouts/title-2content-image.png',
    id: 2
  },
  {
    shapes:[
        { type:'text',
          content: 'Click to add Title',
          x: '30%',
          y: '10%',
          w: '100px',
          h: '30px',
         
        },
        { type:'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '20%',
          y: '66%',
          w: '200px',
          h: '200px',          
        },
        { type:'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '60%',
          y: '66%',
          w: '200px',
          h: '200px',          
        },
      ],
      url:'assets/layouts/title-2image.png',
      id: 3
  },
  {
    shapes:[
        { type: 'text',
          content: 'Click to add Title',
          x: '30%',
          y: '10%',
          w: '100px',
          h: '30px',
        },
        { type: 'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '20%',
          y: '43%',
          w: '200px',
          h: '200px',
        },
        { type: 'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '40%',
          y: '43%',
          w: '200px',
          h: '200px',
        },
        { type: 'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '20%',
          y: '76%',
          w: '300px',
          h: '200px',
        },
    ],
    url: 'assets/layouts/title-3image.png',
    id: 4
  },
  {
    shapes:[
        { type:'text',
          content: 'Click to add Title',
          x: '30%',
          y: '10%',
          w: '100px',
          h: '30px',
        },
        { type:'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '20%',
          y: '43%',
          w: '150px',
          h: '150px',
        },
        { type:'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '60%',
          y: '76%',
          w: '150px',
          h: '150px',
        },
        { type:'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '20%',
          y: '76%',
          w: '150px',
          h: '150px',
        },
        { type:'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '60%',
          y: '76%',
          w: '150px',
          h: '150px',
        },
      ],
      url: 'assets/layouts/title-4image.png',
      id: 5
  },
  {
    shapes: [
        { type:'text',
          content: 'Click to add Title',
          x: '30%',
          y: '10%',
          w: '100px',
          h: '30px',
        },
        { type:'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '15%',
          y: '43%',
          w: '100px',
          h: '100px',
        },
        { type:'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '45%',
          y: '43%',
          w: '100px',
          h: '100px',
        },
        { type:'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '15%',
          y: '43%',
          w: '100px',
          h: '100px',
        },
        { type:'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '15%',
          y: '76%',
          w: '100px',
          h: '100px',
        },
        { type:'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '45%',
          y: '76%',
          w: '100px',
          h: '100px',
        },
        { type:'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '75%',
          y: '76%',
          w: '100px',
          h: '100px',
        },
      ],
      url: 'assets/layouts/title-6image.png',
      id: 6
  },
  {
    shapes: [
        { type:'text',
          content: 'Click to add Title',
          x: '30%',
          y: '10%',
          w: '100px',
          h: '30px',
        },
        { type:'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '35%',
          y: '43%',
          w: '250px',
          h: '250px',
        },
      ],
      url: 'assets/layouts/title-image.png',
      id: 7
  },
  {
    shapes: [
        { type:'text',
          content: 'Click to add Title',
          x: '30%',
          y: '10%',
          w: '100px',
          h: '30px',
        },
        { type:'text',
          content: 'Click to add Text',
          x: '50%',
          y: '43%',
          w: '200px',
          h: '100px',
        },
        { type:'picture',
          content: 'https://pbs.twimg.com/profile_images/528137831542038528/S79NgwqB.png',
          x: '15%',
          y: '73%',
          w: '200px',
          h: '200px',
        },
      ],
     url: 'assets/layouts/title-content-image.png',
     id: 8
  },
  {
    shapes: [
        { type:'text',
          content: 'Click to add Title',
          x: '30%',
          y: '10%',
          w: '100px',
          h: '30px',
        },
        { type:'text',
          content: 'Click to add Text',
          x: '20%',
          y: '43%',
          w: '500px',
          h: '400px',
        },
      ],
      url: 'assets/layouts/title-content.png',
      id: 9
  }
];
export default bringLayouts;